//
//  Decks.swift
//  Evolution
//
//  Created by Matt on 7/27/14.
//  Copyright (c) 2014 Matt. All rights reserved.
//

import Foundation


class DeckList {
    let name: String
    let contents: [(Trait,Int)] // Trait and amount of food
    init(name: String, contents: [(Trait,Int)]){
        self.name = name
        self.contents = contents
    }
    
    func getDeck(game: Game) -> [Card] {
        var cards = [Card]()
        for (trait, food) in contents {
            cards.append(Card(trait: trait, food: food, game: game))
        }
        return cards
    }
}

let standardDeck = DeckList(
    name: "Standard Deck",
    contents:
    [
        (carnivoreTrait, -3),
        (carnivoreTrait, -2),
        (carnivoreTrait, -1),
        (carnivoreTrait, 0),
        (carnivoreTrait, 1),
        (carnivoreTrait, 2),
        (carnivoreTrait, 3),
        (carnivoreTrait, 3),
        (carnivoreTrait, 3),
        (carnivoreTrait, 4),
        (carnivoreTrait, 4),
        (carnivoreTrait, 4),
        (carnivoreTrait, 5),
        (carnivoreTrait, 6),
        (carnivoreTrait, 7),
        (carnivoreTrait, 8),
        (carnivoreTrait, 9),
        (ambushTrait, -3),
        (ambushTrait, -2),
        (ambushTrait, -1),
        (ambushTrait, 0),
        (ambushTrait, 1),
        (ambushTrait, 2),
        (ambushTrait, 3),
        (burrowingTrait, 1),
        (burrowingTrait, 2),
        (burrowingTrait, 3),
        (burrowingTrait, 3),
        (burrowingTrait, 4),
        (burrowingTrait, 4),
        (burrowingTrait, 5),
        (climbingTrait, 1),
        (climbingTrait, 2),
        (climbingTrait, 3),
        (climbingTrait, 3),
        (climbingTrait, 4),
        (climbingTrait, 4),
        (climbingTrait, 5),
        (cooperationTrait, 0),
        (cooperationTrait, 3),
        (cooperationTrait, 3),
        (cooperationTrait, 4),
        (cooperationTrait, 4),
        (cooperationTrait, 5),
        (cooperationTrait, 5),
        (defensiveherdingTrait, 6),
        (defensiveherdingTrait, 6),
        (defensiveherdingTrait, 7),
        (defensiveherdingTrait, 7),
        (defensiveherdingTrait, 8),
        (defensiveherdingTrait, 8),
        (defensiveherdingTrait, 9),
        (fattissueTrait, -1),
        (fattissueTrait, 0),
        (fattissueTrait, 3),
        (fattissueTrait, 4),
        (fattissueTrait, 4),
        (fattissueTrait, 5),
        (fattissueTrait, 5),
        (fertileTrait, 2),
        (fertileTrait, 3),
        (fertileTrait, 4),
        (fertileTrait, 5),
        (fertileTrait, 6),
        (fertileTrait, 6),
        (fertileTrait, 7),
        (foragingTrait, 2),
        (foragingTrait, 3),
        (foragingTrait, 4),
        (foragingTrait, 5),
        (foragingTrait, 6),
        (foragingTrait, 6),
        (foragingTrait, 7),
        (hardshellTrait, 1),
        (hardshellTrait, 2),
        (hardshellTrait, 3),
        (hardshellTrait, 3),
        (hardshellTrait, 4),
        (hardshellTrait, 4),
        (hardshellTrait, 5),
        (hornsTrait, 1),
        (hornsTrait, 2),
        (hornsTrait, 3),
        (hornsTrait, 3),
        (hornsTrait, 4),
        (hornsTrait, 4),
        (hornsTrait, 5),
        (intelligenceTrait, -2),
        (intelligenceTrait, -1),
        (intelligenceTrait, 0),
        (intelligenceTrait, 4),
        (intelligenceTrait, 5),
        (intelligenceTrait, 6),
        (intelligenceTrait, 7),
        (longneckTrait, 6),
        (longneckTrait, 6),
        (longneckTrait, 7),
        (longneckTrait, 7),
        (longneckTrait, 8),
        (longneckTrait, 8),
        (longneckTrait, 9),
        (packhuntingTrait, -3),
        (packhuntingTrait, -2),
        (packhuntingTrait, -1),
        (packhuntingTrait, 0),
        (packhuntingTrait, 1),
        (packhuntingTrait, 2),
        (packhuntingTrait, 3),
        (scavengerTrait, 2),
        (scavengerTrait, 3),
        (scavengerTrait, 4),
        (scavengerTrait, 5),
        (scavengerTrait, 6),
        (scavengerTrait, 6),
        (scavengerTrait, 7),
        (symbiosisTrait, 1),
        (symbiosisTrait, 2),
        (symbiosisTrait, 3),
        (symbiosisTrait, 3),
        (symbiosisTrait, 4),
        (symbiosisTrait, 4),
        (symbiosisTrait, 5),
        (warningcallTrait, 1),
        (warningcallTrait, 2),
        (warningcallTrait, 3),
        (warningcallTrait, 3),
        (warningcallTrait, 4),
        (warningcallTrait, 4),
        (warningcallTrait, 5),
    ]
)


//let standardDeck = DeckList(
//    name: "Standard Deck",
//    cards:
//    [
//        Card(trait: carnivoreTrait, food: -3),
//        Card(trait: carnivoreTrait, food: -2),
//        Card(trait: carnivoreTrait, food: -1),
//        Card(trait: carnivoreTrait, food: 0),
//        Card(trait: carnivoreTrait, food: 1),
//        Card(trait: carnivoreTrait, food: 2),
//        Card(trait: carnivoreTrait, food: 3),
//        Card(trait: carnivoreTrait, food: 3),
//        Card(trait: carnivoreTrait, food: 3),
//        Card(trait: carnivoreTrait, food: 4),
//        Card(trait: carnivoreTrait, food: 4),
//        Card(trait: carnivoreTrait, food: 4),
//        Card(trait: carnivoreTrait, food: 5),
//        Card(trait: carnivoreTrait, food: 6),
//        Card(trait: carnivoreTrait, food: 7),
//        Card(trait: carnivoreTrait, food: 8),
//        Card(trait: carnivoreTrait, food: 9),
//        Card(trait: ambushTrait, food: -3),
//        Card(trait: ambushTrait, food: -2),
//        Card(trait: ambushTrait, food: -1),
//        Card(trait: ambushTrait, food: 0),
//        Card(trait: ambushTrait, food: 1),
//        Card(trait: ambushTrait, food: 2),
//        Card(trait: ambushTrait, food: 3),
//        Card(trait: burrowingTrait, food: 1),
//        Card(trait: burrowingTrait, food: 2),
//        Card(trait: burrowingTrait, food: 3),
//        Card(trait: burrowingTrait, food: 3),
//        Card(trait: burrowingTrait, food: 4),
//        Card(trait: burrowingTrait, food: 4),
//        Card(trait: burrowingTrait, food: 5),
//        Card(trait: climbingTrait, food: 1),
//        Card(trait: climbingTrait, food: 2),
//        Card(trait: climbingTrait, food: 3),
//        Card(trait: climbingTrait, food: 3),
//        Card(trait: climbingTrait, food: 4),
//        Card(trait: climbingTrait, food: 4),
//        Card(trait: climbingTrait, food: 5),
//        Card(trait: cooperationTrait, food: 0),
//        Card(trait: cooperationTrait, food: 3),
//        Card(trait: cooperationTrait, food: 3),
//        Card(trait: cooperationTrait, food: 4),
//        Card(trait: cooperationTrait, food: 4),
//        Card(trait: cooperationTrait, food: 5),
//        Card(trait: cooperationTrait, food: 5),
//        Card(trait: defensiveherdingTrait, food: 6),
//        Card(trait: defensiveherdingTrait, food: 6),
//        Card(trait: defensiveherdingTrait, food: 7),
//        Card(trait: defensiveherdingTrait, food: 7),
//        Card(trait: defensiveherdingTrait, food: 8),
//        Card(trait: defensiveherdingTrait, food: 8),
//        Card(trait: defensiveherdingTrait, food: 9),
//        Card(trait: fattissueTrait, food: -1),
//        Card(trait: fattissueTrait, food: 0),
//        Card(trait: fattissueTrait, food: 3),
//        Card(trait: fattissueTrait, food: 4),
//        Card(trait: fattissueTrait, food: 4),
//        Card(trait: fattissueTrait, food: 5),
//        Card(trait: fattissueTrait, food: 5),
//        Card(trait: fertileTrait, food: 2),
//        Card(trait: fertileTrait, food: 3),
//        Card(trait: fertileTrait, food: 4),
//        Card(trait: fertileTrait, food: 5),
//        Card(trait: fertileTrait, food: 6),
//        Card(trait: fertileTrait, food: 6),
//        Card(trait: fertileTrait, food: 7),
//        Card(trait: foragingTrait, food: 2),
//        Card(trait: foragingTrait, food: 3),
//        Card(trait: foragingTrait, food: 4),
//        Card(trait: foragingTrait, food: 5),
//        Card(trait: foragingTrait, food: 6),
//        Card(trait: foragingTrait, food: 6),
//        Card(trait: foragingTrait, food: 7),
//        Card(trait: hardshellTrait, food: 1),
//        Card(trait: hardshellTrait, food: 2),
//        Card(trait: hardshellTrait, food: 3),
//        Card(trait: hardshellTrait, food: 3),
//        Card(trait: hardshellTrait, food: 4),
//        Card(trait: hardshellTrait, food: 4),
//        Card(trait: hardshellTrait, food: 5),
//        Card(trait: hornsTrait, food: 1),
//        Card(trait: hornsTrait, food: 2),
//        Card(trait: hornsTrait, food: 3),
//        Card(trait: hornsTrait, food: 3),
//        Card(trait: hornsTrait, food: 4),
//        Card(trait: hornsTrait, food: 4),
//        Card(trait: hornsTrait, food: 5),
//        Card(trait: intelligenceTrait, food: -2),
//        Card(trait: intelligenceTrait, food: -1),
//        Card(trait: intelligenceTrait, food: 0),
//        Card(trait: intelligenceTrait, food: 4),
//        Card(trait: intelligenceTrait, food: 5),
//        Card(trait: intelligenceTrait, food: 6),
//        Card(trait: intelligenceTrait, food: 7),
//        Card(trait: longneckTrait, food: 6),
//        Card(trait: longneckTrait, food: 6),
//        Card(trait: longneckTrait, food: 7),
//        Card(trait: longneckTrait, food: 7),
//        Card(trait: longneckTrait, food: 8),
//        Card(trait: longneckTrait, food: 8),
//        Card(trait: longneckTrait, food: 9),
//        Card(trait: packhuntingTrait, food: -3),
//        Card(trait: packhuntingTrait, food: -2),
//        Card(trait: packhuntingTrait, food: -1),
//        Card(trait: packhuntingTrait, food: 0),
//        Card(trait: packhuntingTrait, food: 1),
//        Card(trait: packhuntingTrait, food: 2),
//        Card(trait: packhuntingTrait, food: 3),
//        Card(trait: scavengerTrait, food: 2),
//        Card(trait: scavengerTrait, food: 3),
//        Card(trait: scavengerTrait, food: 4),
//        Card(trait: scavengerTrait, food: 5),
//        Card(trait: scavengerTrait, food: 6),
//        Card(trait: scavengerTrait, food: 6),
//        Card(trait: scavengerTrait, food: 7),
//        Card(trait: symbiosisTrait, food: 1),
//        Card(trait: symbiosisTrait, food: 2),
//        Card(trait: symbiosisTrait, food: 3),
//        Card(trait: symbiosisTrait, food: 3),
//        Card(trait: symbiosisTrait, food: 4),
//        Card(trait: symbiosisTrait, food: 4),
//        Card(trait: symbiosisTrait, food: 5),
//        Card(trait: warningcallTrait, food: 1),
//        Card(trait: warningcallTrait, food: 2),
//        Card(trait: warningcallTrait, food: 3),
//        Card(trait: warningcallTrait, food: 3),
//        Card(trait: warningcallTrait, food: 4),
//        Card(trait: warningcallTrait, food: 4),
//        Card(trait: warningcallTrait, food: 5),
//    ]
//)